# Generated by Django 4.0.4 on 2022-05-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_blurbphoto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlurbPhoto',
        ),
    ]
